# Generated by Django 5.0.4 on 2024-05-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_actions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="email",
            field=models.EmailField(default="", max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name="appuser",
            name="first_name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="appuser",
            name="last_name",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
