# Generated by Django 5.0.4 on 2024-05-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_actions", "0002_appuser_email_appuser_first_name_appuser_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
