# Generated by Django 5.0.6 on 2024-05-07 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserVaccination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.appuser"
                    ),
                ),
                (
                    "vaccination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.vaccination",
                    ),
                ),
            ],
        ),
    ]
