# Generated by Django 5.0.6 on 2024-05-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_uservaccination"),
    ]

    operations = [
        migrations.AddField(
            model_name="vaccination",
            name="total_doses",
            field=models.IntegerField(default=1, null=True),
        ),
    ]
