# Generated by Django 5.0.6 on 2024-05-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_vaccination_total_doses"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appuser",
            name="age",
        ),
        migrations.AddField(
            model_name="appuser",
            name="birth_date",
            field=models.DateField(null=True),
        ),
    ]
