# Generated by Django 5.0.6 on 2024-05-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_remove_appuser_age_appuser_birth_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="region",
        ),
        migrations.AddField(
            model_name="address",
            name="zip_code",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
