# Generated by Django 5.0.6 on 2024-05-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_remove_address_region_address_zip_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="vaccination",
            name="yearly",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="vaccination",
            name="total_doses",
            field=models.IntegerField(null=True),
        ),
    ]
