# Generated by Django 5.0.6 on 2024-06-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_vaccination_yearly_alter_vaccination_total_doses"),
    ]

    operations = [
        migrations.CreateModel(
            name="YearlyVaccination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("optional", models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name="vaccination",
            name="yearly",
        ),
    ]
