# Generated by Django 5.0.6 on 2024-06-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_uservaccination_yearly_vaccination_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="uservaccination",
            name="date",
            field=models.DateField(null=True),
        ),
    ]
